heat_template_version: queens
description: >
  Software Config to drive os-net-config with 2 bonded nics on a bridge with VLANs attached for the ComputeDVR role.
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  BondInterfaceOvsOptions:
    default: bond_mode=active-backup
    description: 'The ovs_options or bonding_options string for the bond
      interface. Set things like lacp=active and/or bond_mode=balance-slb
      for OVS bonds or like mode=4 for Linux bonds using this option.'
    type: string
  ExternalNetworkVlanID:
    default: 10
    description: Vlan ID for the external network traffic.
    type: number
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ExternalInterfaceDefaultRoute:
    default: '169.47.188.1'
    description: default route for the external network
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /home/stack/templates/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:

              - type: linux_bond
                name: bond0
                mtu: 9000
                use_dhcp: false
                bonding_options: "mode=4 miimon=100 downdelay=0 updelay=0 lacp_rate=fast xmit_hash_policy=1"
                members:
                - type: interface
                  name: enp1s0f0
                  mtu: 9000
                  primary: true
                - type: interface
                  mtu: 9000
                  name: enp2s0f0
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
                - ip_netmask: 169.254.169.254/32
                  next_hop:
                    get_param: EC2MetadataIp
                - ip_netmask: 10.0.0.0/8
                  next_hop: 10.211.62.1
                - ip_netmask: 161.26.0.0/16
                  next_hop: 10.211.62.1
                - ip_netmask: 166.8.0.0/14
                  next_hop: 10.211.62.1
                dns_servers:
                  get_param: DnsServers

              - type: ovs_bridge
                name: bridge_name
                addresses:
                - ip_netmask: {get_param: ExternalIpSubnet}
                routes:
                - default: true
                  next_hop: {get_param: ExternalInterfaceDefaultRoute}
                dns_servers:
                  get_param: DnsServers
                members:
                - type: linux_bond
                  name: bond1
                  bonding_options: "mode=4 miimon=100 downdelay=0 updelay=0 lacp_rate=fast xmit_hash_policy=1"
                  members:
                  - type: interface
                    name: enp1s0f1
                    primary: true
                  - type: interface
                    name: enp2s0f1

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl
