---
collections:
  - community.general
  - oasis_roles.system
  # the satellite collection doesn't seem to be published to galaxy yet, and we don't have support
  # for cloning git repos for collections, for now use the install_satellite_collection.sh
  #- oasis_roles.satellite
  #- name: https://github.com/oasis-roles/ansible_collection_satellite/tree/main
  #  type: git
  - ovirt.ovirt
  - theforeman.foreman
  - tripleo.operator
  - dellemc.openmanage
...
