---
- hosts: all
  connection: local
  name: Update firmware
  gather_facts: False
  collections:
    - community.general

  tasks:
  - include_tasks: idrac_update.yml
    vars:
      update_version: "{{ version }}"
    loop: "{{ oob.firmware.versions }}"
    loop_control:
      loop_var: version
    when: 
      - "'Dell' in oob.SystemManufacturer"
  - include_tasks: update.yml
    vars:
      update_version: "{{ version }}"
    loop: "{{ oob.firmware.versions }}"
    loop_control:
      loop_var: version
    when: 
      - "'Dell' not in oob.SystemManufacturer"
...