---
- hosts: test
  connection: local
  name: Get BIOS attributes
  gather_facts: False
  collections:
    - community.general

  vars:
    datatype: VirtualMedia
    baseuri: "{{ inventory_hostname }}"

  tasks:
  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get VirtualMedia status
    redfish_info:
      category: Manager
      command: GetVirtualMedia
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result
    delegate_to: localhost
    
  - debug:
      msg: "{{ result.redfish_facts | to_nice_yaml }}"
      verbosity: 2

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_yaml }}"
      dest: "{{ template }}.yml"
...