---
- hosts: baremetal
  connection: local
  name: View all storage configuration
  gather_facts: False
  vars:
    # Optionally specify a controller if desired, default is all via 'null'
    # e.g. idrac_controller_id: "AHCI.Slot.4-1"
    idrac_controller_id: null
    idrac_volaume_id: null

  tasks:
    - name: View all volumes
      dellemc_idrac_storage_volume:
        idrac_ip: "{{ oob.ipaddr }}"
        idrac_user: "{{ oob_username }}"
        idrac_password: "{{ oob_password }}"
        state: "view"
        controller_id: "{{ idrac_controller_id | default(omit) }}"
        volume_id: "{{ idrac_volume_id | default(omit) }}"
      register: view_result

    - debug:
        var: view_result
        verbosity: 1
...