---
- hosts: baremetal
  connection: local
  name: View all storage configuration
  gather_facts: False
  collections:
    - dellemc.openmanage
  vars:
    # Optionally specify a controller if desired
    # e.g. idrac_controller_id: "AHCI.Slot.4-1"
    idrac_controller_id: "{{ oob.storage.virtual_disks.os.controller_id }}"

  tasks:
    - name: View all volumes
      dellemc_idrac_storage_volume:
        idrac_ip: "{{ oob.ipaddr }}"
        idrac_user: "{{ oob_username }}"
        idrac_password: "{{ oob_password }}"
        state: "view"
        controller_id: "{{ idrac_controller_id | default(omit) }}"
      register: view_result

    - debug:
        var: view_result
        verbosity: 1

    - debug:
        var: view_result.storage_status.Message[idrac_controller_id].VirtualDisk
      when: view_result.storage_status.Message[idrac_controller_id].VirtualDisk is defined | default(False)
...
