---
- name: Configure Repos and install Guac Servers
  hosts: gsrv 
  gather_facts: true
  vars:
    nginx_firewalld_services:
      - ssh
      - http

  tasks:
    - name: Unsubscribe from satellite due to bug with epel
      redhat_subscription:
        state: absent
    - name: Re-subscribe to satellite
      redhat_subscription:
        state: present
        server_hostname: satellite.dal10.ole.redhat.com
        org_id: GLS
        activationkey: RHEL7-VMs-Key
        auto_attach: yes
    - name: Update packages using yum
      yum:
        name: "*"
        state: latest
    - name: Install git
      yum:
        name: "git"
        state: present
    - name: Install nginx 1.18 from RHCL
      yum:
        name: "rh-nginx18"
        state: present
    - name: Register host ID from short hostname assuming vnc0x
      shell: "hostname -s |cut -c5"
      register: id_from_host
    - name: Configure nginx default.conf
      template:
        src: templates/nginx_default.conf.j2
        dest: /etc/opt/rh/rh-nginx18/nginx/conf.d/default.conf
    - name: Configure nginx.conf
      template:
        src: templates/nginx.conf.j2
        dest: /etc/opt/rh/rh-nginx18/nginx/nginx.conf
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
    - name: Make sure a service is running
      systemd:
        state: started
        name: firewalld
    - name: Enable firewall services for NGINX in public zone
      firewalld:
        service: "{{ item }}"
        zone: public
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ nginx_firewalld_services }}"
    - name: Enable and start NGINX
      systemd:
        name: rh-nginx18-nginx.service
        state: started
        enabled: yes
    - name: Import ssh key for git access
      copy:
        src: files/git_deploy_rsa
        dest: "/root/.ssh/id_rsa"
        mode: 0600
    - name: Clone novello-guacamole.git
      git:
        repo: git@github.com:RedHatTraining/novello-guacamole.git
        dest: "{{ guac_git_location }}"
        accept_hostkey: yes
    - name: Install podman
      yum:
        name: "podman"
        state: present
    - name: Podman build guac
      command: podman build --no-cache -t guacamole-jwt .
      args:
        chdir: "{{guac_git_location }}/usr/local/src/guacamole-client"
    - name: Set SELINUX for podman
      seboolean:
        name: container_manage_cgroup
        state: yes
        persistent: yes
    - name: Clean up previous guac_web pod install
      shell: "podman container rm -f guacamole_web"
      ignore_errors: yes
    - name: Clean up previous guac_base pod install
      shell: "podman container rm -f guacamole_web"
      ignore_errors: yes
    - name: Run Guac Daemon
      shell: "podman run --net host --name base-guacd -e GUACD_LOG_LEVEL=debug -d guacamole/guacd"
    - name: Create systemd service script for Guac Base
      template:
        src: templates/guacamole-base-podman.service.j2
        dest: /etc/systemd/system/guacamole-base-podman.service
    - name: Run Guac web server
      shell: "podman run --name guacamole_web -p 8080:8080 --net=host -e GUACD_HOSTNAME=localhost -e GUACD_PORT=4822 -e JWT_SECRET_KEY={{ guac_secret_key }} -d guacamole-jwt"
    - name: Create systemd service script for Guac Pod
      template:
        src: templates/guacamole-podman.service.j2
        dest: /etc/systemd/system/guacamole-podman.service
    - name: Enable and start Guacamole Base
      systemd:
        name: guacamole-base-podman.service
        state: started
        enabled: yes
    - name: Enable and start Guacamole Web Services
      systemd:
        name: guacamole-podman.service
        state: started
        enabled: yes

    - name: Enable and start Guacamole
      systemd:
        name: guacamole-podman.service
        state: started
        enabled: yes
