---
- import_playbook: get_inventory.yml

- hosts: baremetal
  connection: local
  name: Update firmware for "{{ oob.manager_name }}" 
  gather_facts: False
  serial: 1
  collections:
    - community.general


  tasks:
  - include_tasks: idrac_update.yml
    vars:
      update_version: "{{ version }}"
    loop: "{{ oob.firmware.versions | difference(installed_versions) }}"
    loop_control:
      loop_var: version
    when: 
      - "'Dell' in oob.SystemManufacturer"

  - include_tasks: update.yml
    vars:
      update_version: "{{ version }}"
    loop: "{{ oob.firmware.versions | difference(installed_versions) }}"
    loop_control:
      loop_var: version
    when: 
      - "'Dell' not in oob.SystemManufacturer"
...