---
# groups['rhvh'][0] is also utilized within the playbook. If you update
# this host group, those references should be as well.
- hosts: rhvh[0]
  gather_facts: no
  tasks:
    ################
    # Authenticate
    ################

    - name: Obtain SSO token with using username/password credentials
      ovirt_auth: "{{ ovirt.auth }}"
      delegate_to: localhost
      tags:
        - always

    ################
    # Attach storage
    ################

    - name: Add hosts
      ovirt_host:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: "{{ item }}"
        address: "{{ item }}"
        password: redhat
      loop: "{{ groups['rhvh'] }}"
      delegate_to: localhost
      tags:
        - host

    ################
    # Attach storage
    ################

    - name: Attach storage domains
      ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        name: "{{ item.name }}"
        host: "{{ groups['rhvh'][0] }}"
        data_center: "{{ item.data_center }}"
        iscsi:
          target: "{{ item.iscsi_target }}"
          lun_id:
          - "{{ item.iscsi_lun_id }}"
          address: "{{ item.iscsi_address }}"
          override_luns: yes
        discard_after_delete: True
        backup: False
        critical_space_action_blocker: 5
        warning_low_space: 10
      loop: "{{ ovirt.storage.domains }}"
      delegate_to: localhost
      tags:
        - storage

    ################
    # Create disks
    ################

    ## TODO
    # need to add the .cer cert here; otherwise upload doesn't work
    # and restart ovirt-imageio-daemon, ovirt-imageio-proxy, it seems

    - name: Download images onto {{ groups['rhvh'][0] }}
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop: "{{ ovirt.get_urls }}"
      tags:
        - disk

    - name: Upload image
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ item.name }}"
        upload_image_path: "{{ item.upload_image_path }}"
        size: "{{ item.size | default(omit) }}"
        storage_domain: "{{ item.storage_domain }}"
        wait: true
        bootable: "{{ item.bootable }}"
        format: "{{ item.format }}"
        content_type: "{{ item.content_type }}"
        timeout: 1800
      loop: "{{ ovirt.storage.disks }}"
      tags:
        - disk

    ################
    # Create networks
    ################

    - name: Create ovirt networks
      ovirt_network:
        auth: "{{ ovirt_auth }}"
        name: "{{ item.value.name }}"
        vlan_tag: "{{ item.value.vlan_tag }}"
        vm_network: yes
        mtu: "{{ item.value.mtu }}"
        data_center: Default
        wait: yes
        clusters:
          - name: Default
            assigned: yes
            display: no
            gluster: no
            migration: "{{ item.value.migration | default(omit) }}"
            required: yes
      loop: "{{ ovirt.networks | dict2items }}"
      delegate_to: localhost
      tags:
        - network

    - name: Create ovirt vnic profiles
      ovirt_vnic_profile:
        auth: "{{ ovirt_auth }}"
        name: "{{ item.value.name }}"
        network: "{{ item.value.name }}"
        state: present
        data_center: Default
      loop: "{{ ovirt.networks | dict2items }}"
      delegate_to: localhost
      tags:
        - network

    - name: Initialize host_networks to empty list
      set_fact:
        host_networks: []
      delegate_to: localhost
      tags:
        - network

    - name: Set host_networks
      set_fact:
        host_networks: "{{ host_networks + hostvars[item].ovirt_host_networks }}"
      loop: "{{ groups['rhvh'] }}"
      delegate_to: localhost
      tags:
        - network

    - ovirt_host_network: "{{ item | combine({'auth': ovirt_auth}) }}"
      loop: "{{ host_networks }}"
      delegate_to: localhost
      tags:
        - network
...
