---
- hosts: rhvh
  name: Initial bootstrapping
  tasks:
    - name: Set hostname
      vars:
        hostname_inject_hosts_files: false
      import_role:
        name: oasis_roles.system.hostname
      tags:
        - hostname

    - name: Inject forward DNS entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ ansible_default_ipv4.address }}"
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"

    - include_tasks: ../../generic/rhsm_register_satellite.yml

    # The following command task is not yet supported in a module, see https://github.com/ansible/ansible/issues/64852
    - name: Reset virt module
      command: yum --assumeyes module reset virt

    # The following command task is not yet supported in a module, see https://github.com/ansible/ansible/issues/64852
    - name: Enable virt module
      command: yum --assumeyes module enable virt:8.2

    - import_tasks: ../../generic/update_system.yml

    # The following command task is not yet supported in a module, see https://github.com/ansible/ansible/issues/64852
    - name: Synchronize installed packages
      command: yum --assumeyes distro-sync

    - name: Install packages
      vars:
        packages: "{{ rhsm.packages }}"
      yum:
        name: "{{ packages }}"
        state: installed
      tags:
        - packages

    - name: Ensure Cockpit is an active service in the firewall
      vars:
        firewalld_services: "{{ firewalld.firewalld_services }}"
        firewalld_zone: "{{ firewalld.firewalld_zone }}"
      import_role:
        name: oasis_roles.system.firewalld

    - name: Enable and start cockpit service
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes

    - name: Set Ansible logging for future debugging
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: log_path
        value: /var/log/ansible.log

    # Network setup needs to be done after, at least, the yum portion because
    # this is dependent on the bridge-utils package which is installed by
    # the rhvm-appliance package.
    - name: Configure networking
      vars:
        # The network-scripts portion of the role is considered a provisioning
        # step. By default, it is not ran unless this is override to yes. When
        # re-running this role, it is probably not ideal to re-setup and restart
        # networking. Which will happen when setup_nics=yes.
        base_setup_nics: "{{ setup_nics | default('no') }}"
      block:
        - name: "Include network-scripts role to template /etc/sysconfig/network-scripts. Use `-e setup_nics=yes` to run."
          vars:
            network_scripts_dest_path: /etc/sysconfig/network-scripts
            network_scripts_nics: "{{ nics | mandatory }}"
            network_scripts_clear_existing: yes
            network_scripts_restart: yes
          include_role:
            name: network-scripts
      when: base_setup_nics | bool
      tags:
        - network

- import_playbook: ../get_ceph_facts/get_iscsi_wwid.yml
  vars:
    ceph_admin_node: "{{ groups['ceph'].0 }}"
    # Engine size
    iscsi_size: "{{ hostvars[ceph_admin_node].ceph.iscsi_targets.images.0.size | upper }}"
  tags:
    - install

- hosts:
    - rhvh
    - rhvh_dev
  name: "Install RHV Manager on {{ inventory_hostname }}"
  tags:
    - install
  vars:
    ceph_admin_node: "{{ groups['ceph'].0 }}"
    # Engine size
    rhv:
      he_lun_id: "{{ hostvars[groups['iscsi_client'].0].iscsi_wwid.stdout }}"
    rhvm_initial_host: "{{ inventory_hostname }}"
  tasks:
    - block:
      - name: Install RHV-M Appliance
        yum:
          name: rhvm-appliance
          state: installed

      - debug:
          var: hostvars[rhvm_initial_host].rhv
          verbosity: 1

      - debug:
          var: rhv
          verbosity: 1

      - name: Run hosted-engine-setup using ovirt-ansible-hosted-engine-setup RPM
        command: >
          ansible-playbook
            -i "localhost,"
            -c local
            {% if ansible_verbosity > 0 %}--verbose{% endif %}
            {% if ansible_verbosity > 1 %}--verbose{% endif %}
            {% if ansible_verbosity > 2 %}--verbose{% endif %}
            {% if ansible_verbosity > 3 %}--verbose{% endif %}
            {% for k,v in rhv.items() -%}
            -e {{ k }}='{{ v }}'
            {% endfor -%}
            /usr/share/ovirt-hosted-engine-setup/ansible/trigger_role.yml
      when: inventory_hostname is match(groups['rhvh_dev'].0)
...
