---
- import_playbook: ../../generic/extend_root_lv.yml
  vars:
    playbook_hosts: rhvh
  tags:
    - setup

- hosts: rhvh
  name: Initial bootstrapping
  tasks:
    - name: Set hostname
      vars:
        hostname_inject_hosts_files: false
      import_role:
        name: oasis_roles.system.hostname
      tags:
        - hostname

    - name: Inject forward DNS entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ ansible_default_ipv4.address }}"
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"

    - include_tasks: ../../generic/rhsm_register_satellite.yml

    # The following command task is not yet supported in a module, see https://github.com/ansible/ansible/issues/64852
    - name: Reset virt module
      command: yum --assumeyes module reset virt

    # The following command task is not yet supported in a module, see https://github.com/ansible/ansible/issues/64852
    - name: Enable virt module
      command: yum --assumeyes module enable virt:8.2

    - import_tasks: ../../generic/update_system.yml

    # The following command task is not yet supported in a module, see https://github.com/ansible/ansible/issues/64852
    - name: Synchronize installed packages
      command: yum --assumeyes distro-sync

    - name: Install packages
      vars:
        packages: "{{ rhsm.packages }}"
      yum:
        name: "{{ packages }}"
        state: installed
      tags:
        - packages

    - name: Ensure Cockpit is an active service in the firewall
      vars:
        firewalld_services: "{{ firewalld.firewalld_services }}"
        firewalld_zone: "{{ firewalld.firewalld_zone }}"
      import_role:
        name: oasis_roles.system.firewalld

    - name: Enable and start cockpit service
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes

    - name: Set Ansible logging for future debugging
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: log_path
        value: /var/log/ansible.log

- import_playbook: ../../generic/network_setup.yml
  vars:
    playbook_hosts: rhvh
  tags:
    - network

- import_playbook: fix_hosted_engine_network.yml
  tags:
    - network

- import_playbook: ../read/get_iscsi_wwid.yml
  vars:
    ceph_admin_node: "{{ groups['ceph'].0 }}"
    # Engine size
    iscsi_size: "{{ hostvars[ceph_admin_node].ceph.iscsi_targets.images.0.size }}"
  tags:
    - install

- hosts: "{{ rhvm_initial_host | default(groups['rhvh'].0) }}"
  name: Install RHV Manager on initial RHVH host
  tags:
    - install
  vars:
    rhvm_initial_host: "{{ groups['rhvh'].0 }}"
    ceph_admin_node: "{{ groups['ceph'].0 }}"
    rhv:
      # Engine iSCSI LUN ID obtained in previous playbook
      he_lun_id: "{{ hostvars[groups['iscsi_client'].0].iscsi_wwid.stdout }}"
  tasks:
    - name: Install RHV-M Appliance
      yum:
        name: rhvm-appliance
        state: installed

    - debug:
        var: hostvars[rhvm_initial_host].rhv
        verbosity: 1

    - debug:
        var: rhv
        verbosity: 1

    - set_fact:
        rhv_he_playbook_cmd: >
          ansible-playbook
            --inventory "localhost,"
            --connection local
            {% if ansible_verbosity > 0 %}--verbose{% endif %}
            {% if ansible_verbosity > 1 %}--verbose{% endif %}
            {% if ansible_verbosity > 2 %}--verbose{% endif %}
            {% if ansible_verbosity > 3 %}--verbose{% endif %}
            {% for k,v in rhv.items() -%}
            --extra-vars {{ k }}='{{ v }}'
            {% endfor -%}
            /usr/share/ovirt-hosted-engine-setup/ansible/trigger_role.yml

    - debug:
        var: rhv_he_playbook_cmd

    - name: Run hosted-engine-setup using ovirt-ansible-hosted-engine-setup RPM
      command: "{{ rhv_he_playbook_cmd }}"
...
