- hosts: rhvm[0]
  remote_user: root
  gather_facts: no
  tasks:
    ################
    # Authenticate
    ################

    - name: Obtain SSO token with using username/password credentials
      ovirt_auth: "{{ ovirt.auth }}"
      run_once: yes
      tags:
        - always

    ################
    # Create disks
    ################

    ## TODO
    # need to add the .cer cert here; otherwise upload doesn't work
    # and restart ovirt-imageio-daemon, ovirt-imageio-proxy, it seems

    - name: Download images onto {{ groups['rhvm'][0] }}
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop: "{{ ovirt.get_urls }}"
      tags:
        - disk

    - name: Create disks
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ item.name }}"
        upload_image_path: "{{ item.upload_image_path | default(omit) }}"
        size: "{{ item.size | default(omit) }}"
        storage_domain: "{{ item.storage_domain }}"
        wait: true
        bootable: "{{ item.bootable }}"
        format: "{{ item.format }}"
        content_type: "{{ item.content_type }}"
        timeout: 1800
        interface: "{{ item.interface | default(omit) }}"
      loop: "{{ ovirt.storage.disks }}"
      tags:
        - disk

    ################
    # Create virtual machines
    ################

    - name: Create virtual machines
      ovirt_vm: "{{ item | combine({'auth': ovirt_auth}) }}"
      loop: "{{ ovirt.vms }}"
      run_once: yes
      tags:
        - vm
