- hosts: rhv
  gather_facts: no
  tasks:
    ################
    # Authenticate
    ################

    - name: Obtain SSO token with using username/password credentials
      ovirt_auth: "{{ ovirt.auth }}"
      delegate_to: localhost
      run_once: yes
      tags:
        - always

    ################
    # Create virtual machines
    ################

    - name: Create virtual machines
      ovirt_vm: "{{ item | combine({'auth': ovirt_auth}) }}"
      loop: "{{ ovirt.vms }}"
      delegate_to: localhost
      run_once: yes
      tags:
        - vm
