- hosts: rhv_dev
  gather_facts: no
  tasks:
    ################
    # Authenticate
    ################

    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: https://ovirt-engine.escwq.com/ovirt-engine/api
        username: admin@internal
        password: "{{ ovirt.password }}"
        insecure: yes
      delegate_to: localhost
      tags:
        - always

    ################
    # Create virtual machines
    ################

    - set_fact:
        vms_list: []
      delegate_to: localhost
      tags:
        - vm

    - set_fact:
        vms_list: "{{ vms_list + [item | combine({'auth': ovirt_auth})] }}"
      delegate_to: localhost
      loop: "{{ ovirt.vms }}"
      tags:
        - vm

    - name: Create virtual machines
      ovirt_vm: "{{ item }}"
      loop: "{{ vms_list }}"
      delegate_to: localhost
      tags:
        - vm
