---
- name: Add ceph automation group
  group:
    name: "{{ ceph_automation_username }}"
    state: present

- name: Add ceph automation user
  user:
    name: "{{ ceph_automation_username }}"
    password: "{{ ceph_automation_password }}"
    group: "{{ ceph_automation_username }}"
    append: yes
    state: present
    createhome: yes

- name: Ensure automation user has sudo access
  lineinfile:
    path: /etc/sudoers.d/{{ ceph_automation_username }}
    state: present
    create: yes
    regexp: '^{{ ceph_automation_username }}'
    line: '{{ ceph_automation_username }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    mode: '0400'

- name: Add authorized key
  authorized_key:
    user: "{{ ceph_automation_username }}"
    state: present
    key: "{{ ssh_key }}"
  loop: "{{ ssh_keys }}"
  loop_control:
    loop_var: ssh_key
...
