- job:
    name: pb-apply-kvm
    run: pb-apply-kvm.yml
    vars:
      datacenter: foo
      named_env: test
      disable_prompt: yes
      kvm:
        hostname: zuul-ci.example.com
    nodeset:
      nodes:
        - name: kvm
          label: centos7

- project:
    check:
      jobs:
        - pb-apply-kvm
    gate:
      jobs:
        - pb-apply-kvm
