---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vars_prompt_message: Confirm the environment to target
    vars_prompt_expected: "{{ datacenter }}-{{ named_env }}"
    vars_prompt_disable: "{{ disable_prompt | default('no') }}"
  roles:
    - vars-prompt
  tags:
    - always



- hosts: director
  name: Apply base, subscription, and director roles
  tasks:
    - name: Subscribe system
      vars:
        subscription: "{{ undercloud.subscription }}"
      import_role:
        name: subscription
      when: "'subscription' in undercloud"
      tags:
        - subscription

    - name: Apply base role
      vars:
        base: "{{ undercloud }}"
      import_role:
        name: base
      tags:
        - base

    - name: Apply director role
      import_role:
        name: director
