---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vars_prompt_message: Confirm the environment to target
    vars_prompt_expected: "{{ datacenter }}-{{ named_env }}"
    vars_prompt_disable: "{{ disable_prompt | default('no') }}"
  roles:
    - vars-prompt
  tags:
    - always



- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - assert:
        that:
          - kvm is defined
        fail_msg: "Variable `kvm` must be defined."

    - assert:
        that:
          - kvm.hostname is defined
        fail_msg: "Variable `kvm.hostname` must be defined."



- hosts: kvm
  tasks:
    - vars:
        subscription: "{{ kvm.subscription }}"
      import_role:
        name: subscription
      tags:
        - subscription
      when: "kvm is defined and 'subscription' in kvm"

    - name: Install bridge-utils to ifup bridges
      yum:
        name: bridge-utils
        state: installed

    - name: Setup networking by clearing existing NIC configs and placing new ones
      vars:
        # The network-scripts portion of the role is considered a provisioning
        # step. By default, it is not ran unless this is override to yes. When
        # re-running this role, it is probably not ideal to re-setup and restart
        # networking. Which will happen when setup_nics=yes.
        base_setup_nics: "{{ setup_nics | default('no') }}"
      block:
        - name: "Include network-scripts role to template
            /etc/sysconfig/network-scripts. Use `-e setup_nics=yes` to run."
          vars:
            network_scripts_dest_path: /etc/sysconfig/network-scripts
            network_scripts_nics: "{{ kvm.nics }}"
            network_scripts_clear_existing: yes
            network_scripts_restart: yes
          include_role:
            name: network-scripts
          when: "'nics' in kvm"

      when: base_setup_nics | bool
      tags:
        - network

    - vars:
        base: "{{ kvm }}"
      import_role:
        name: base
      tags:
        - base

    - import_role:
        name: kvm
      tags:
        - kvm

    - name: yum update
      yum:
        name: '*'
        state: latest



- hosts: kvm
  tasks:
    - include_role:
        name: libvirt
      with_items: "{{ kvm.libvirt.domains }}"
      loop_control:
        loop_var: domain
      when: "kvm is defined and 'libvirt' in kvm"

  tags:
    - libvirt
