---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    full_env: "{{ datacenter }}-{{ named_env }}"
  vars_prompt:
    - name: prompt_env
      prompt: Confirm the environment to target
      private: no
  tasks:
    - assert:
        that:
          - prompt_env.strip() == full_env
        fail_msg: "Incorrect environment entered. {{ prompt_env }} is not \
          {{ full_env }}"
        success_msg: "Targeting {{ prompt_env.strip() }} environment"

  tags:
    - always

- hosts: director
  tasks:
    - import_role:
        name: director
