---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vars_prompt_message: Confirm the environment to target
    vars_prompt_expected: "{{ datacenter }}-{{ named_env }}"
    vars_prompt_disable: "{{ disable_prompt | default('no') }}"
  roles:
    - vars-prompt
  tags:
    - always



- hosts: overcloud
  tasks:
    - vars:
        subscription: "{{ base.subscription }}"
      import_role:
        name: subscription
      tags:
        - subscription
      when: "subscription is defined"
