---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
    - name: prompt_env
      prompt: Confirm the environment to target
      private: no
  tasks:
    - assert:
        that:
          - prompt_env == named_env
        fail_msg: "Incorrect environment entered. {{ prompt_env }} is not {{ named_env }}"
        success_msg: "Targeting {{ prompt_env }} environment"

  tags:
    - always

- hosts: director
  tasks:
    - import_role:
        name: director
