---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vars_prompt_message: Confirm the environment to target
    vars_prompt_expected: "{{ datacenter }}-{{ named_env }}"
    vars_prompt_disable: "{{ disable_prompt | default('no') }}"
  roles:
    - vars-prompt
  tags:
    - always



- hosts: director
  become: yes
  become_user: stack
  tasks:
    # Upload the latest output templates to the director
    - block:
        - name: Ensure ansible-generated exists on director
          file:
            path: '/home/stack/ansible-generated/'
            state: directory
            owner: stack
            group: stack
            mode: '0755'

        - name: Create /home/stack/ansible-generated directory structure
          file:
            path: "/home/stack/ansible-generated/{{ item.path }}"
            state: directory
            owner: stack
            group: stack
          with_filetree: "ansible-generated/{{ datacenter }}-{{ named_env }}"
          when: item.state == 'directory'

        - name: Template ansible-generated/ deployment files to director
          template:
            src: "{{ item.src }}"
            dest: "/home/stack/ansible-generated/{{ item.path }}"
            owner: stack
            group: stack
            mode: preserve
          with_filetree: "ansible-generated/{{ datacenter }}-{{ named_env }}"
          when: item.state == 'file'

    # Attempt to deploy the overcloud.
    # If success, print the stack status
    # If failure, print the failures
    - block:
        - name: openstack overcloud deploy
          shell: |
            cd ~ &&
            source ~/stackrc && \
            ~/ansible-generated/scripts/deploy.sh
          async: 5400
          poll: 60

        - name: openstack stack list
          shell: |
            source ~/stackrc && \
            openstack stack list
          register: shell_output
          changed_when: false

        - debug:
            var: shell_output.stdout_lines
          changed_when: false

      rescue:
        - name: openstack stack failures list
          shell: |
            source ~/stackrc && \
            openstack stack failures list overcloud-{{ named_env }} | \
            sed 's/\\n/\n/g'
          register: shell_output
          changed_when: false

        - debug:
            var: shell_output.stdout_lines
          changed_when: false
