- hosts: localhost
  gather_facts: no
  vars:
    pb_tmp_dir: "/tmp/ansible-generated/{{ named_env }}"
    pb_output_dir: "./ansible-generated"
  tasks:
    - name: Ensure {{ pb_tmp_dir }} doesn't already exist
      file:
        path: "{{ pb_tmp_dir }}"
        state: absent
      changed_when: false

    # # Template ./roles/osp-templates/templates into $pb_tmp_dir
    # - include_role:
    #     name: template-directory
    #   vars:
    #     template_directory_input_dir: roles/template-directory/templates/
    #     template_directory_output_dir: "{{ pb_tmp_dir }}"
    #     template_directory_changed_when: false
    #   no_log: true

    # Template ../inventory/{{ datacenter }}/templates into $pb_tmp_dir
    - include_role:
        name: template-directory
      vars:
        template_directory_input_dir: "../ansible-inventory/{{ datacenter }}/templates/"
        template_directory_output_dir: "{{ pb_tmp_dir }}"
        template_directory_changed_when: false
      no_log: true

    # Copy $pb_tmp_dir into $pb_output_dir
    - include_role:
        name: template-directory
      vars:
        template_directory_input_dir: "{{ pb_tmp_dir }}"
        template_directory_output_dir: "{{ pb_output_dir }}"
        template_directory_changed_when: true
        template_directory_copy_only: true
