- hosts: localhost
  gather_facts: no
  vars:
    shared_dir: "../ansible-inventory/{{ datacenter }}/templates/shared/"
    cluster_dir: "../ansible-inventory/{{ datacenter }}/templates/{{ named_env }}/"
    tmp_dir: "/tmp/ansible-generated/{{ datacenter }}/{{ named_env }}"
    output_dir: "../ansible-inventory/{{ datacenter }}/ansible-generated"
    quick: no
  tasks:
    - name: Ensure {{ tmp_dir }} doesn't already exist
      file:
        path: "{{ tmp_dir }}"
        state: absent
      changed_when: false

    # Template $shared_dir into $tmp_dir
    - include_role:
        name: template-directory
      vars:
        template_directory_input_dir: "{{ shared_dir }}"
        template_directory_output_dir: "{{ tmp_dir }}"
        template_directory_changed_when: false
        template_directory_quick_mode: "{{ quick|bool }}"
      no_log: true

    # Template $cluster_dir into $tmp_dir
    - include_role:
        name: template-directory
      vars:
        template_directory_input_dir: "{{ cluster_dir }}"
        template_directory_output_dir: "{{ tmp_dir }}"
        template_directory_changed_when: false
        template_directory_quick_mode: "{{ quick|bool }}"
      no_log: true

    # Copy $tmp_dir into $output_dir
    - include_role:
        name: template-directory
      vars:
        template_directory_input_dir: "{{ tmp_dir }}"
        template_directory_output_dir: "{{ output_dir }}"
        template_directory_changed_when: true
        template_directory_quick_mode: false
        template_directory_copy_only: true
