---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    full_env: "{{ datacenter }}-{{ named_env }}"
  vars_prompt:
    - name: prompt_env
      prompt: Confirm the environment to target
      private: no
  tasks:
    - assert:
        that:
          - prompt_env.strip() == full_env
        fail_msg: "Incorrect environment entered. {{ prompt_env }} is not \
          {{ full_env }}"
        success_msg: "Targeting {{ prompt_env.strip() }} environment"

  tags:
    - always



- hosts: director
  name: Unregister director
  become: yes
  become_user: root
  tasks:
    - name: Unregister director
      redhat_subscription:
        state: absent
  tags:
    - director



- hosts: kvm
  name: Remove director and controller domains
  become: yes
  become_user: root
  tasks:
    - name: Destroy domains
      virt:
        name: "{{ item.name }}"
        state: destroyed
      loop: "{{ kvm.libvirt.domains }}"

    - name: Undefine domains
      virt:
        name: "{{ item.name }}"
        command: undefine
      loop: "{{ kvm.libvirt.domains }}"

    - name: Delete volumes
      shell: virsh vol-delete --pool images {{ item.name }}.qcow2
      loop: "{{ kvm.libvirt.domains }}"

  tags:
    - libvirt
