- debug:
    msg: "staging_ovirt driver: {{ node.value.name }}"
    verbosity: 1

- name: Set credential facts
  set_fact:
    pm_addr: "{{ rhv.he_fqdn }}"
    pm_user: "{{ rhv_admin_username }}@internal"
    pm_password: "{{ rhv_admin_password }}"

- name: Authenticate with rhv-m
  ovirt_auth: "{{ ovirt.auth }}"
  delegate_to: localhost
  when: ovirt_auth is undefined

- name: Grab the eth0 information for the current node
  ovirt_nic_info:
    auth: "{{ ovirt_auth }}"
    vm: "{{ node.value.pm_vm_name }}"
    name: eth0
  delegate_to: localhost
  register: result

- debug:
    msg: "{{ node.value.pm_vm_name }}: {{ result.ovirt_nics[0].mac.address }}"
    verbosity: 1

- name: Update the node object with the found MAC address
  vars:
    update:
      mac:
      - "{{ result.ovirt_nics[0].mac.address | lower }}"
      pm_addr: "{{ pm_addr }}"
      pm_user: "{{ pm_user }}"
      pm_password: "{{ pm_password }}"
  set_fact:
    node_with_mac: "{{ node.value | combine(update) }}"

- name: Add the updated node to instackenv
  set_fact:
    instackenv: "{{ instackenv + [node_with_mac] }}"
