---
- name: Check for required variables
  hosts: director
  connection: local
  gather_facts: no
  tasks:
    - block:
        - fail:
            msg: "{{ item }} is not defined"
          when: item is undefined
          loop:
            - "{{ site_name }}"

- name: Add director host to the Ansible group of the site being added
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    - name: Set site_to_add fact
      set_fact:
        site_to_add: "site_{{ site_name }}"

    - name: Add director host to the correct site group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ group_names + [site_to_add] }}"

- name: Upload ansible-generated templates
  import_playbook: blocks/upload-ansible-generated-templates.yml

- name: openstack undercloud install
  import_playbook: blocks/openstack-undercloud-install.yml
  tags:
    - openstack undercloud install

- name: openstack overcloud deploy central
  import_playbook: blocks/openstack-overcloud-deploy.yml
  vars:
    dcn_export: yes
    tripleo_overcloud_deploy_stack: central
    tripleo_overcloud_deploy_networks_file: "{{ site.central.deploy_networks_file }}"
    tripleo_overcloud_deploy_roles_file: "{{ site.central.deploy_roles_file }}"
    tripleo_overcloud_deploy_environment_files: "{{ site.central.deploy_environment_files }}"
  tags:
    - openstack ovecloud deploy central

- name: openstack overcloud node import
  import_playbook: blocks/openstack-overcloud-node-import.yml
  vars:
    tripleo_overcloud_node_import_environment_file: /home/stack/ansible-generated/instackenv.yaml
  tags:
    - openstack overcloud node import

- name: Map Neutron ports to baremetal nodes
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    - name: Map Neutron ports to baremetal nodes
      shell: /home/stack/ansible-generated/scripts/_map_neutron_ports.sh
  tags:
    - map neutron ports

- name: openstack overcloud node introspect
  import_playbook: blocks/openstack-overcloud-node-introspect.yml
  tags:
    - openstack overcloud node introspect

- name: Create roles for Overcloud nodes
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    - name: Create roles for Overcloud nodes
      become: yes
      become_user: stack
      shell: /home/stack/ansible-generated/scripts/_create_roles.sh
  tags:
    - create roles

- name: "openstack overcloud deploy {{ site_name }}"
  import_playbook: blocks/openstack-overcloud-deploy.yml
  vars:
    dcn_export: no
    tripleo_overcloud_deploy_stack: "{{ site_name }}"
    tripleo_overcloud_deploy_networks_file: "{{ site[site_name].deploy_networks_file }}"
    tripleo_overcloud_deploy_roles_file: "{{ site[site_name].deploy_roles_file }}"
    tripleo_overcloud_deploy_environment_files: "{{ site[site_name].deploy_environment_files }}"
  tags:
    - openstack overcloud deploy site_name

- name: "openstack aggregate create {{ site_name }}"
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    - shell: |
        source /home/stack/centralrc

        openstack aggregate create --zone {{ site_name }} {{ site_name }}
  tags:
    - openstack aggregate create site_name

# - name: tempest run central
#   import_playbook: blocks/tempest-run.yml
#   vars:
#     tempest_workspace: central
#   tags:
#     - tempest run central

# - name: tempest run {{ site_name }}
#   import_playbook: blocks/tempest-run.yml
#   vars:
#     tempest_workspace: "{{ site_name }}"
#   tags:
#     - tempest run site_name
...
