---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vars_prompt_message: Confirm the environment to target
    vars_prompt_expected: "{{ datacenter }}-{{ named_env }}"
    vars_prompt_disable: "{{ disable_prompt | default('no') }}"
  roles:
    - vars-prompt

  tags:
    - always



- hosts: director
  become: yes
  become_user: root
  ignore_unreachable: yes
  name: Unregister director
  tasks:
    - name: Unregister director
      redhat_subscription:
        state: absent

  tags:
    - director



- hosts: kvm
  name: Remove director and controller domains
  become: yes
  become_user: root
  tasks:
    - name: Destroy domains
      virt:
        name: "{{ item.name }}"
        state: destroyed
      loop: "{{ kvm.libvirt.domains }}"

    - name: Undefine domains
      virt:
        name: "{{ item.name }}"
        command: undefine
      loop: "{{ kvm.libvirt.domains }}"

    - name: Delete volumes
      shell: virsh vol-delete --pool images {{ item.name }}.qcow2
      loop: "{{ kvm.libvirt.domains }}"

  tags:
    - libvirt
