# - name: 4.2. Running the overcloud update preparation
#   hosts: director
#   become: yes
#   become_user: stack
#   gather_facts: no
#   tasks:
#     - block:
#         - name: openstack overcloud update prepare
#           shell: |
#             cd ~ &&
#             source ~/stackrc && \
#             ~/ansible-generated/scripts/overcloud-update-prepare.sh
#           async: 3600
#           poll: 30

#       rescue:
#         - debug:
#             msg: rescue

#       always:
#         - debug:
#             msg: always



# - name: 4.3. Updating all Controller nodes
#   hosts: director
#   become: yes
#   become_user: stack
#   gather_facts: no
#   tasks:
#     - block:
#         - name: openstack overcloud update run --nodes Controller
#           shell: |
#             cd ~ &&
#             source ~/stackrc && \
#             openstack overcloud update run --nodes Controller
#           async: 3600
#           poll: 30

#       rescue:
#         - debug:
#             msg: rescue

#       always:
#         - debug:
#             msg: always



# - name: 4.4. Updating all ComputeDVR nodes
#   hosts: director
#   become: yes
#   become_user: stack
#   gather_facts: no
#   tasks:
#     - block:
#         - name: v
#           shell: |
#             cd ~ &&
#             source ~/stackrc && \
#             openstack overcloud update run --nodes ComputeDVR
#           async: 3600
#           poll: 30

#       rescue:
#         - debug:
#             msg: rescue

#       always:
#         - debug:
#             msg: always



# - name: 4.7. Finalizing the update
#   hosts: director
#   become: yes
#   become_user: stack
#   gather_facts: no
#   tasks:
#     - block:
#         - name: openstack overcloud update converge
#           shell: |
#             cd ~ &&
#             source ~/stackrc && \
#             ~/ansible-generated/scripts/overcloud-update-converge.sh
#           async: 3600
#           poll: 30

#       rescue:
#         - debug:
#             msg: rescue

#       always:
#         - debug:
#             msg: always
