heat_template_version: queens

description: Create networks to split out Overcloud traffic

resources:
  ExternalNetwork:
    type: OS::TripleO::Network::External

  NetworkExtraConfig:
    type: OS::TripleO::Network::ExtraConfig


outputs:
  net_cidr_map:
    value:
      # NOTE(gfidente): we need to replace the null value with a
      # string to work around https://bugs.launchpad.net/heat/+bug/1700025
      external:
        yaql:
          data: {get_attr: [ExternalNetwork, subnet_cidr]}
          expression: str($.data).replace('null', 'disabled')