---
- name: Check for required variables
  hosts: director
  connection: local
  gather_facts: no
  tasks:
    - block:
        - fail:
            msg: "{{ item }} is not defined"
          when: item is undefined
          loop:
            - "{{ site_name }}"

#
# Upload new templates?
#

- name: "openstack overcloud delete {{ site_name }}"
  import_playbook: ../blocks/openstack-overcloud-delete.yml
  vars:
    tripleo_overcloud_delete_name: "{{ site_name }}"

- name: Tempest run
  import_playbook: ../misc/tempest-run.yml
  vars:
    site_name: central
    network_name: management-central-net
  tags:
    - tempest run
...
