---
- name: Create Satellite VM
  hosts: kvm_hypervisor
  gather_facts: False
  tasks:
  - name: Create Satellite KVM VM
    import_role:
      name: kvm_vm
    vars:
      kvm_vm: "{{ hostvars[groups['satellite'].0].kvm_vm }}"
    tags:
      - setup
...
