---
- hosts: baremetal
  connection: local
  name: Set BIOS attribute - All
  gather_facts: False
  collections:
    - community.general

  # BIOS attributes that have been tested
  #
  # Name                  Value
  # --------------------------------------------------
  # LogicalProc           Disabled / Enabled

  tasks: 
  - name: Set BIOS attributes
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes: "{{ oob.config.BIOS.All }}"
      baseuri: "{{ oob.ipaddr }}"
      username: "{{ oob_username }}"
      password: "{{ oob_password }}"
    register: bios_attribute

  # DELL BIOS ONLY: Updating BIOS settings requires creating a configuration job
  # to schedule the BIOS update, so comment out below for non-Dell systems.

  - name: Create BIOS configuration job (schedule BIOS setting update)
    idrac_redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ oob.ipaddr }}"
      username: "{{ oob_username }}"
      password: "{{ oob_password }}"
    when:
      - "'Dell' in oob.SystemManufacturer"
      
# Switching from redfish reboot to OS reboot and then iDRAC reboot
#  - name: Reboot system to apply new BIOS settings
#    redfish_command:
#      category: Systems
#      command: PowerReboot
#      baseuri: "{{ oob.ipaddr }}"
#      username: "{{ oob_username }}"
#      password: "{{ oob_password }}"
#    when: 
#      - "'Dell' in oob.SystemManufacturer"
      
- name: Reboot via OS 
  reboot:
    post_reboot_delay: 300
    reboot_timeout: 900
  delegate_to: "{{ inventory_hostname }}"
  when: not no_os | default(False)
  register: os_reboot_result
  ignore_errors: yes

- block:
    - import_tasks: ../actions/reboot_server.yml

    - name: Wait until iDRAC is available
      wait_for:
        host: "{{ oob.ipaddr }}"
        port: 22
        delay: 300
        timeout: 900
  when: >
    no_os | default(False) or
    os_reboot_result is failed
...