#resource_registry:
#  OS::TripleO::Controller::Net::SoftwareConfig: net-config-linux-bridge-controller.yaml
#  OS::TripleO::ComputeDVR::Net::SoftwareConfig: net-config-linux-bridge.yaml

resource_registry:
  OS::TripleO::ComputeDVR::PreNetworkConfig: /home/stack/ansible-generated/templates/custom/nested_virt_host_config_and_reboot.yaml

parameter_defaults:
  ControllerCount: 3
  OvercloudControllerFlavor: control
  ComputeDVRCount: 2
  OvercloudComputeDVRFlavor: compute

  ComputeDVRExtraConfig:
    nova::compute::vnc_keymap: ''
    nova::cpu_allocation_ratio: '12.0'
    nova::compute::libvirt::libvirt_cpu_mode: 'host-passthrough'

  ExtraConfig:
    tripleo::firewall::firewall_rules:
      '300 Prometheus exporter':
        port: 9100
        proto: tcp
        action: accept
    nova::config::nova_config:
      'filter_scheduler/build_failure_weight_multiplier':
        value: 0
    nova::compute::force_config_drive: false
