parameter_defaults:
  CephClientKey: {{ overcloud.ceph.CephClientKey }}
  CephClusterFSID: 32159b3f-a9cc-41fa-afde-84b8cc29b90d
  CephExternalMonHost: 10.221.23.230, 10.221.23.231, 10.221.23.232

  CephClientUserName: openstack
  NovaRbdPoolName: piggy_nova
  CinderRbdPoolName: piggy_cinder
  GlanceRbdPoolName: piggy_glance
  GnocchiRbdPoolName: piggy_metrics
