parameter_defaults:
  CephClientKey: {{ overcloud.ceph.CephClientKey }}
  CephClusterFSID: a2eb52b9-5f58-4884-b4aa-38a07486ea95
  CephExternalMonHost: 10.221.23.230, 10.221.23.231, 10.221.23.232

  CephClientUserName: openstack
  NovaRbdPoolName: piggy_nova
  CinderRbdPoolName: piggy_cinder
  GlanceRbdPoolName: piggy_glance
  GnocchiRbdPoolName: piggy_metrics
