parameter_defaults:
  CephClientKey: {{ overcloud.ceph.CephClientKey }}
  CephClusterFSID: 719ea386-f65e-424a-bfd5-937e933b1dec
  CephExternalMonHost: 10.221.23.230, 10.221.23.231, 10.221.23.232

  CephClientUserName: openstack
  NovaRbdPoolName: piggy_nova
  CinderRbdPoolName: piggy_cinder
  GlanceRbdPoolName: piggy_glance
  GnocchiRbdPoolName: piggy_metrics
