---
- name: Destroy iSCSI Targets on deployed Ceph Cluster
  hosts: "{{ ceph_admin_node | default(groups['ceph'].0) }}"
  gather_facts: False
  become: True
  vars:
    ceph_automation_username: ceph_ansible
    ceph_admin_node: "{{ groups['ceph'].0 }}"
  remote_user: "{{ ceph_automation_username }}"
  tasks:
    - when: inventory_hostname is match(ceph_admin_node)
      block:
        - name: Copy playbook to Ceph admin node {{ ceph_admin_node }}
          template:
            src: ../templates/iscsi_target_destroy.yml.j2
            dest: ~/iscsi_target_destroy.yml
        - name: Run playbook on Ceph admin node {{ ceph_admin_node }}
          command: >
            ansible-playbook
              --inventory "rbd-target-api,"
              --connection podman
              {% if ansible_verbosity > 0 %}--verbose{% endif %}
              {% if ansible_verbosity > 1 %}--verbose{% endif %}
              {% if ansible_verbosity > 2 %}--verbose{% endif %}
              {% if ansible_verbosity > 3 %}--verbose{% endif %}
              ~/iscsi_target_destroy.yml
          environment:
            ANSIBLE_LOG_PATH: ~/iscsi_target_destroy.log
...
