---
# This playbook runs the purge playbook

- name: Purge and cleanup cluster
  hosts: ceph
  gather_facts: True
  vars:
    # Which cluster group to operate on
    ceph_automation_username: ceph_ansible
    ceph_admin_node: "{{ groups['ceph'].0 }}"
    ceph_playbook_dir: /usr/share/ceph-ansible
    ceph_playbook: purge-container-cluster.yml
    ceph_inventory: /etc/ansible/hosts
    ceph_playbook_command: >
      ansible-playbook
      --inventory {{ ceph_inventory }}
      --user {{ ceph_automation_username }}
      {% if ansible_verbosity > 0 %}--verbose{% endif %}
      {% if ansible_verbosity > 1 %}--verbose{% endif %}
      {% if ansible_verbosity > 2 %}--verbose{% endif %}
      {% if ansible_verbosity > 3 %}--verbose{% endif %}
      {% for k,v in rhv.items() -%}
      {{ ceph_playbook }}
  remote_user: "{{ ceph_automation_username }}"
  tasks:
    - name: Ensure playbooks are in place
      copy:
        dest: /usr/share/ceph-ansible/{{ ceph_playbook }}
        src: /usr/share/ceph-ansible/infrastructure-playbooks/{{ ceph_playbook }}
        remote_src: yes
      become: yes

    - name: Display run command for ceph-ansible
      debug:
        msg: "{{ ceph_playbook_command }}"
        verbosity: 1

    - name: Run {{ ceph_playbook }}
      command: "{{ ceph_playbook_command }}"
      args:
        chdir: "{{ ceph_playbook_dir }}"
      environment:
        ANSIBLE_CONFIG: "{{ ceph_playbook_dir }}/ansible.cfg"
      register: ceph_ansible_playbook_run

    - debug:
        var: ceph_ansible_playbook_run
        verbosity: 1
...
