---
- name: Setup prerequisites
  hosts: satellite
  become: yes
  become_user: root
  tasks:
    - name: Register server with CDN
      vars:
        rhsm_repositories: "{{ rhsm.rhsm_repositories }}"
      import_role:
        name: oasis_roles.system.rhsm
      tags:
        - rhsm

    - name: enable required guest services
      vars:
        services: "{{ rhsm.services }}"
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      tags:
        - services

    - name: Set hostname
      vars:
        hostname_inject_hosts_files: false
      import_role:
        name: oasis_roles.system.hostname
      tags:
        - hostname

<<<<<<< HEAD
    - name: Inject forward DNS entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ ansible_default_ipv4.address }}"
        line: "{{ ansible_host }} {{ ansible_fqdn }} {{ ansible_hostname }}"

    - name: Set firewall
      vars:
        firewalld_zone: "{{ firewalld.firewalld_zone }}"
        firewalld_ports_open: "{{ firewalld.firewalld_ports_open }}"
      import_role:
        name: oasis_roles.system.firewalld

=======
>>>>>>> d5c189734651a0e712d6e7a37b2170e90fab12ee
  tags:
    - prereq


- name: Setup Satellite
  hosts: satellite
  become: yes
  become_user: root
  tasks:
    - vars:
        satellite_server_url:  "{{ satellite.server_url }}"
        satellite_hostname: "{{ ansible_hostname }}"
        satellite_domain: "{{ dns_domain }}"
        satellite_hostip: "{{ ansible_default_ipv4.address }}"
        satellite_options: "{{ satellite.options }}"
        satellite_packages: "{{ rhsm.packages}}"
      import_role:
        name: oasis_roles.satellite.install
  tags:
    - setup
...
