---
- name: Setup prerequisites
  hosts: satellite
  become: yes
  become_user: root
  tasks:
    - name: Register server with CDN
      vars:
        rhsm_repositories: "{{ rhsm.rhsm_repositories }}"
      import_role:
        name: oasis_roles.system.rhsm
      tags:
        - rhsm

    - name: Install ovirt-guest-agent-common
      yum:
        name: ovirt-guest-agent-common
        state: installed

    - name: Enable required guest services
      vars:
        services: "{{ rhsm.services }}"
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      tags:
        - services

    - name: Set hostname
      vars:
        hostname_inject_hosts_files: false
      import_role:
        name: oasis_roles.system.hostname
      tags:
        - hostname

  tags:
    - prereq


- name: Setup Satellite
  hosts: satellite
  become: yes
  become_user: root
  tasks:
    - vars:
        satellite_server_url:  "{{ satellite.server_url }}"
        satellite_hostname: "{{ ansible_hostname }}"
        satellite_domain: "{{ dns_domain }}"
        satellite_hostip: "{{ satellite_infra.listen_address }}"
        satellite_options: "{{ satellite.options }}"
        satellite_packages: "{{ rhsm.packages}}"
      import_role:
        name: oasis_roles.satellite.install
  tags:
    - setup
...
