---
fpga_satellite_info:
  server: my-satellite.example.com
  key: realtime-example
  org: Default
  epel_repo: Default_EPEL8_epel8

fpga_packages:
  epel:
    - dkms
  opae_tools:
    - opae
    - opae-tools
    - opae-tools-extra
    - opae.admin
    - opae-intel-fpga-driver
  opae_fw:
    - opae-one-time-update-n3000-25G
    - opae-super-rsu-n3000-2x2x25G

fpga_files:
  loc: http://localhost/fpga_files
  bitstream:
    4g: turbo4g_2x1x25g_2fvl_unsigned_20ww01.bin
    5g: 20ww14.5-2x2x25G-5GLDPC-v1.5.7-3.0.0-unsigned.bin

fpga_want_bitstream: 4g

fpga_want_build:
  n3000_2: v1_1
  n3000_n: v1_3

fpga_reboot_timeout: 1800
...
