---
- name: Load variables based on major OS version
  include_vars:
    file: "vars/RedHat-{{ kvm_vm.os_variant.split('rhel')[-1].split('.')[0]}}.yml"

- name: list all VMs
  virt:
    command: list_vms
  register: libvirt_vms

- debug:
    var: libvirt_vms
    verbosity: 1

- name: Teardown KVM VM
  include_tasks: teardown_vm.yml
  when:
    - libvirt_vms.list_vms is search(kvm_vm.name)
    - teardown | default(False)
- block:
    - name: Create KVM VM
      include_tasks: create_vm.yml
      when:
        - not create_empty_vm | default(False)

    - name: Create Empty KVM VM
      include_tasks: create_empty_vm.yml
      when:
        - create_empty_vm | default(False)
  when:
    - not libvirt_vms.list_vms is search(kvm_vm.name)
    - not teardown | default(False)
...
