---
- block:
    - name: Remove KVM VM
      virt:
        command: "{{ action }}"
        name: "{{ kvm_vm.name }}"
      loop:
        - destroy
        - undefine
      loop_control:
        loop_var: action

    - name: Remove KVM disk
      file:
        path: "{{ kvm_vm_dir }}/{{ kvm_vm.disk }}"
        state: absent

    - name: Remove Ceph KVM disks
      file:
        path: "{{ kvm_vm_dir }}/{{ disk }}"
        state: absent
      loop:
        - "{{ kvm_vm.disk_vdb }}"
        - "{{ kvm_vm.disk_vdc }}"
      loop_control:
        loop_var: disk
      when: teardown_ceph_secondry_disks | default(False)
...
