heat_template_version: newton

description: >
  This Heat stack will create the initial Overcloud networking
  resources for baremetal and virtual hosts. Also creates a test network and
  subnet to be used by Tempest.

parameters:

resources:
  provider_network:
    type: OS::Neutron::ProviderNet
    properties:
      network_type: flat
      physical_network: datacentre
      router_external: true
      shared: true
      name: provider-network

  provider_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: provider_network }
      cidr: 150.238.9.128/26
      gateway_ip: 150.238.9.129
      allocation_pools:
        - start: 150.238.9.152
          end: 150.238.9.190
      enable_dhcp: true
      name: provider-subnet

  tempest_network:
    type: OS::Neutron::Net
    properties:
      name: ansible-generated-tempest-network
      shared: true

  tempest_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: tempest_network }
      cidr: 192.168.0.0/24
      gateway_ip: 192.168.0.1
      enable_dhcp: true
      name: ansible-generated-tempest-subnet
