---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vars_prompt_message: Confirm the environment to target
    vars_prompt_expected: "{{ datacenter }}-{{ named_env }}"
    vars_prompt_disable: "{{ disable_prompt | default('no') }}"
  roles:
    - vars-prompt
  tags:
    - always



- hosts: director
  become: yes
  become_user: stack
  tasks:
    # Upload the latest output templates to the director
    - block:
        - name: Ensure ansible-generated exists on director
          file:
            path: '/home/stack/ansible-generated/'
            state: directory
            owner: stack
            group: stack
            mode: '0755'

        - name: Create /home/stack/ansible-generated directory structure
          file:
            path: "/home/stack/ansible-generated/{{ item.path }}"
            state: directory
            owner: stack
            group: stack
          with_filetree: "{{ inventory_dir }}/../ansible-generated/{{ named_env }}"
          when: item.state == 'directory'

        - name: Template ansible-generated/ deployment files to director
          template:
            src: "{{ item.src }}"
            dest: "/home/stack/ansible-generated/{{ item.path }}"
            owner: stack
            group: stack
            mode: preserve
          with_filetree: "{{ inventory_dir }}/../ansible-generated/{{ named_env }}"
          when: item.state == 'file'
      tags:
        - templates

    # Attempt to deploy the overcloud.
    # If success, print the stack status
    # If failure, print the failures
    - block:
        - name: openstack overcloud deploy
          import_role:
            name: tripleo.operator.tripleo_overcloud_deploy
          vars:
            CNF: /home/stack/ansible-generated/templates
            THT: /usr/share/openstack-tripleo-heat-templates
            tripleo_overcloud_deploy_debug: true
            tripleo_overcloud_deploy_environment_files: "{{ overcloud.environment_files }}"
            tripleo_overcloud_deploy_home_dir: /home/stack
            tripleo_overcloud_deploy_log_output: false
            tripleo_overcloud_deploy_networks_file: "{{ overcloud.networks_file }}"
            tripleo_overcloud_deploy_roles_file: "{{ overcloud.roles_file }}"
            tripleo_overcloud_deploy_stack: "{{ overcloud.stack_name }}"
            tripleo_overcloud_deploy_timeout: 7200
            tripleo_overcloud_deploy_poll: 60

        - debug:
            var: tripleo_overcloud_deploy_result.stdout_lines

        - name: openstack stack list
          shell: |
            source ~/stackrc && \
            openstack stack list
          register: shell_output
          changed_when: false

        - debug:
            var: shell_output.stdout_lines
          changed_when: false

      rescue:
        - name: openstack stack failures list
          shell: |
            source ~/stackrc && \
            openstack stack failures list overcloud-{{ named_env }} | \
            sed 's/\\n/\n/g'
          register: shell_output
          changed_when: false

        - debug:
            var: shell_output.stdout_lines
          changed_when: false

      tags:
        - deploy
