parameter_defaults:
  ServiceNetMap:
    ApacheNetwork: ctlplane
    NeutronTenantNetwork: ctlplane
    AodhApiNetwork: ctlplane
    PankoApiNetwork: ctlplane
    BarbicanApiNetwork: ctlplane
    GnocchiApiNetwork: ctlplane
    MongodbNetwork: ctlplane
    CinderApiNetwork: ctlplane
    CinderIscsiNetwork: ctlplane
    CongressApiNetwork: ctlplane
    GlanceApiNetwork: ctlplane
    IronicApiNetwork: ctlplane
    IronicNetwork: ctlplane
    IronicInspectorNetwork: ctlplane
    KeystoneAdminApiNetwork: ctlplane 
    KeystonePublicApiNetwork: external
    ManilaApiNetwork: ctlplane
    MetricsQdrNetwork: ctlplane
    NeutronApiNetwork: ctlplane
    OctaviaApiNetwork: ctlplane
    HeatApiNetwork: ctlplane
    HeatApiCfnNetwork: ctlplane
    HeatApiCloudwatchNetwork: ctlplane
    NovaApiNetwork: ctlplane
    NovaPlacementNetwork: ctlplane
    NovaMetadataNetwork: ctlplane
    NovaVncProxyNetwork: ctlplane
    NovaLibvirtNetwork: ctlplane
    NovajoinNetwork: ctlplane
    Ec2ApiNetwork: ctlplane
    Ec2ApiMetadataNetwork: ctlplane
    TackerApiNetwork: ctlplane
    SwiftStorageNetwork: ctlplane
    SwiftProxyNetwork: ctlplane
    SaharaApiNetwork: ctlplane
    HorizonNetwork: external
    MemcachedNetwork: ctlplane
    OsloMessagingRpcNetwork: ctlplane
    OsloMessagingNotifyNetwork: ctlplane
    RabbitmqNetwork: ctlplane
    QdrNetwork: ctlplane
    RedisNetwork: ctlplane
    GaneshaNetwork: ctlplane
    MysqlNetwork: ctlplane
    SnmpdNetwork: ctrlplane
    CephClusterNetwork: ctlplane
    CephMonNetwork: ctlplane
    CephRgwNetwork: ctlplane
    PublicNetwork: external
    OpendaylightApiNetwork: ctlplane
    OvnDbsNetwork: ctlplane
    MistralApiNetwork: ctlplane
    ZaqarApiNetwork: ctlplane
    DockerRegistryNetwork: ctlplane
    PacemakerRemoteNetwork: ctlplane
    TripleoUINetwork: ctlplane
    DesignateApiNetwork: ctlplane
    BINDNetwork: external
    CephStorageHostnameResolveNetwork: ctlplane
    EtcdNetwork: ctlplane
    OpenshiftMasterNetwork: ctlplane
    OpenshiftInfraNetwork: ctlplane
    ControllerHostnameResolveNetwork: ctlplane
    ComputeDVRHostnameResolveNetwork: ctlplane
