{% import jinja_macros_dir + '/get_physnet_mapping.j2' as macros %}
{% set site_upper = loop_index.name_upper %}
{% set site_lower = loop_index.name_lower %}
{% set role_name = 'ComputeVdu' + loop_index.name_upper %}
{{ role_name }}Image: overcloud-realtime-compute

{{ role_name }}ExtraConfig:
  nova::cpu_allocation_ratio: 1
  nova::compute::resume_guests_state_on_host_boot: true
  nova::pci::aliases:
    - name: vc_fpga
      vendor_id: '1172'
      product_id: '5050'
      device_type: 'type-VF'

{{ role_name }}Parameters:
  KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=350 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
  IsolCpusList:  2-39,42-79
  # switch to NovaVcpuPinSet as work around for bz-1835705
  #NovaComputeCpuDedicatedSet:  2-39,42-79
  NovaVcpuPinSet: 2-39,42-79
  NovaComputeCpuSharedSet:  0,1,40,41
  NovaEnableRbdBackend: false
  NeutronPhysicalDevMappings:
    {{ macros.get_all_physnet_mappings(network_roles, 'ComputeVdu', site_lower, "- %(physnet)s-%(site)s:%(nic)s") | indent(4) | trim }}
  NeutronSriovNumVFs:
    - p3p1:4
    - p3p2:4
    - p8p1:4
    - p8p2:4
    - p1p1:2
    - p1p3:2
    - p4p1:2
    - p4p3:2
  NovaPCIPassthrough:
    {{ macros.get_all_physnet_mappings(network_roles, 'ComputeVdu', site_lower, "- devname: %(nic)s\n  physical_network: %(physnet)s-%(site)s") | indent(4) | trim }}
    - vendor_id: "1172"
      product_id: "5050"
