resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-config/controller.yaml
  OS::TripleO::ComputeDVR::Net::SoftwareConfig: /home/stack/templates/nic-config/computedvr.yaml

