#resource_registry:
#  OS::TripleO::Controller::Net::SoftwareConfig: net-config-linux-bridge-controller.yaml
#  OS::TripleO::ComputeDVR::Net::SoftwareConfig: net-config-linux-bridge.yaml

resource_registry:
  OS::TripleO::ComputeDVR::PreNetworkConfig: /home/stack/ansible-generated/templates/custom/nested_virt_host_config_and_reboot.yaml


parameter_defaults:
  ControllerCount: 3
  OvercloudControllerFlavor: control
  ComputeDVRCount: 7
  OvercloudComputeDVRFlavor: compute

  ComputeDVRExtraConfig:
    nova::compute::vnc_keymap: ''
    nova::cpu_allocation_ratio: '32.0'
    nova::compute::libvirt::libvirt_cpu_mode: 'host-passthrough'
    nova::compute::libvirt::config::libvirtd_config:
      vnc_listen:
        value: 0.0.0.0

  ExtraConfig:
    tripleo::firewall::firewall_rules:
      '300 Prometheus exporter':
        port: 9100
        proto: tcp
        action: accept
      '301 Prometheus ceph-mgr plugin':
        port: 9283
        proto: tcp
        action: accept
    nova::config::nova_config:
      'filter_scheduler/build_failure_weight_multiplier':
        value: 1
