parameter_defaults:
  CephClientKey: AQDKY75dAAAAABAA1TAKj7Qml22vvS+W6UcU9A==
  CephClusterFSID: 6ca2f0a1-74c9-4eae-ba99-d5fe319584ac
  CephExternalMonHost: 10.221.21.230, 10.221.21.231, 10.221.21.232
  CephClientUserName: openstack
  NovaRbdPoolName: dal10_nova
  CinderRbdPoolName: dal10_cinder
  GlanceRbdPoolName: dal10_glance
