parameter_defaults:
  CephClientKey: {{ overcloud.ceph.CephClientKey }}
  CephClusterFSID: 816c4b92-feaa-4e02-9a96-a9824f50a90f
  CephExternalMonHost: 10.221.21.230, 10.221.21.231, 10.221.21.232

  CephClientUserName: openstack
  NovaRbdPoolName: kermit_nova
  CinderRbdPoolName: kermit_cinder
  GlanceRbdPoolName: kermit_glance
  GnocchiRbdPoolName: kermit_metrics
