heat_template_version: queens

parameters:
  ControlPlaneIp:
    default: ''
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  ExternalIp:
    default: ''
    type: string
  ExternalIpSubnet:
    description: 'IP address/subnet on the external network'
    default: ''
    type: string
  ExternalIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  ExternalNetName:
    default: external
    description: The name of the external network.
    type: string

resources:

  NetIpMapValue:
    type: OS::Heat::Value
    properties:
      type: json
      value:
        map_replace:
          - ctlplane: {get_param: ControlPlaneIp}
            external: {get_param: ExternalIp}
            ctlplane_subnet:
              list_join:
                - ''
                - - {get_param: ControlPlaneIp}
                  - '/'
                  - {get_param: ControlPlaneSubnetCidr}
            external_subnet: {get_param: ExternalIpSubnet}
            ctlplane_uri: {get_param: ControlPlaneIp}
            external_uri: {get_param: ExternalIpUri}
          - keys:
              external: {get_param: ExternalNetName}
              external_subnet:
                str_replace:
                  template: NAME_subnet
                  params:
                    NAME: {get_param: ExternalNetName}
              external_uri:
                str_replace:
                  template: NAME_uri
                  params:
                    NAME: {get_param: ExternalNetName}

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned IPs
      for a specific machine.
    value: {get_attr: [NetIpMapValue, value]}