heat_template_version: queens

parameters:
  # Set these via parameter defaults to configure external VIPs
  ControlPlaneIP:
    default: ''
    type: string
  ExternalNetworkVip:
    default: ''
    type: string
  # The following are unused in this template
  ControlPlaneIp:
    default: ''
    type: string
  ExternalIp:
    default: ''
    type: string
  ExternalIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned IPs
      for a specific machine.
    value:
      ctlplane: {get_param: ControlPlaneIP}
      external: {get_param: ExternalNetworkVip}
      ctlplane_uri: {get_param: ControlPlaneIP}
      external_uri:
        list_join:
          - ''
          - - '['
            - {get_param: ExternalNetworkVip}
            - ']'