---
- hosts: all
  connection: local
  name: Set One Time Boot device
  gather_facts: False
  collections:
    - community.general
  vars:
    boot_order:
      - HardDisk.List.1-1
      - NIC.Integrated.1-1-1
      - Floppy.iDRACVirtual.1-1
      - Optical.iDRACVirtual.1-1

  tasks:
  - block:
      - name: Set BootOrder
        redfish_config:
          category: Systems
          command:
            - SetBootOrder
          resource_id: "{{ oob.resource_ids.system }}"
          boot_order:
          baseuri: "{{ oob.ipaddr }}"
          username: "{{ oob.username }}"
          password: "{{ oob.password }}"

      - debug:
          var: onetimeboot_result
          verbosity: 2

    tags:
      - bootorder
    # Possible fallback if not a Dell
    # This task sets a new permanent boot order, so a callback after install is done needs to set it back
    # Relative attribute: "SetBootOrderEn": "HardDisk.List.1-1,NIC.Integrated.1-1-1,Floppy.iDRACVirtual.1-1,Optical.iDRACVirtual.1-1",
    #EndBlock

  - block:
      - name: Create BIOS configuration job (schedule BIOS setting update)
        idrac_redfish_command:
          category: Systems
          command: CreateBiosConfigJob
          baseuri: "{{ oob.ipaddr }}"
          username: "{{ oob.username }}"
          password: "{{ oob.password }}"
    tags:
      - configjob
    when:
      - "'Dell' in oob.SystemManufacturer"
    #EndBlock
...