---
- import_playbook: blocks/generate-instackenv.yml

- hosts: director
  connection: local
  gather_facts: no
  tasks:
    - set_fact:
        output_dir: "templates/{{ template_pack }}/.tmp"
        # This relative path **has** to be in the current directory or a subdirectory.
        # It **cannot** lead thru a parent directory. This is due to the
        # jinja2 macro import being used within the templates, no current workaround exists.
        relative_path_to_templates: "templates/{{ template_pack }}"

    - include_tasks: "{{ relative_path_to_templates }}/tasks-to-generate-templates.yml"

    - name: Clear out discovered python interpreter
      meta: clear_facts

- name: Upload ansible-generated templates
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  vars:
    templates_dir: "{{ output_dir }}/ansible-generated"
  tasks:
    # Upload the latest output templates to the director
    - block:
        - name: Check if /home/stack/ansible-generated exists
          stat:
            path: /home/stack/ansible-generated
          register: stat_output

        - name: If /home/stack/ansible-generated exists, copy the folder to a backup location
          vars:
            date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
          copy:
            src: /home/stack/ansible-generated
            dest: "/var/tmp/ansible-generated_{{ date }}"
            remote_src: yes
          when: stat_output.stat.exists

        - name: Ensure ansible-generated exists on director
          file:
            path: '/home/stack/ansible-generated/'
            state: directory
            owner: stack
            group: stack
            mode: '0755'

        - name: Create /home/stack/ansible-generated directory structure
          file:
            path: "/home/stack/ansible-generated/{{ item.path }}"
            state: directory
            owner: stack
            group: stack
          with_filetree: "{{ templates_dir }}"
          when: item.state == 'directory'

        - name: Template ansible-generated/ deployment files to director
          template:
            src: "{{ item.src }}"
            dest: "/home/stack/ansible-generated/{{ item.path }}"
            owner: stack
            group: stack
            mode: preserve
          with_filetree: "{{ templates_dir }}"
          when: item.state == 'file'

        - name: Clear out discovered python interpreter
          meta: clear_facts

  tags:
    - upload

- hosts: director
  connection: local
  gather_facts: no
  remote_user: root
  tasks:
    - name: Cleanup .tmp directory
      file:
        path: "{{ output_dir }}"
        state: absent
      tags:
        - cleanup

    - name: Clear out discovered python interpreter
      meta: clear_facts

...
