---
- name: Build custom ISOs pointing to a kickstart for a given list of hosts
  hosts: infra
  gather_facts: False
  become: True
  vars:
    build_iso_hosts: "{{ groups['ceph'] | union(groups['rhvh']) }}"
  tasks:
    - debug:
        var: build_iso_hosts

    - include_role:
        name: build_iso
      vars:
        iso_hostname:  "{{ host }}"
      loop: "{{ build_iso_hosts }}"
      loop_control:
        loop_var: host
...
