---
- hosts: "{{ playbook_hosts | default('ceph,rhvh') }}"
  name: Setup networks
  become: yes
  become_user: root
  tags:
    - network
  tasks:
    - include_role:
        name: linux-system-roles.network
      vars:
        network_allow_restart: yes
...
