---
- name: Install katello package
  yum:
    name: "http://{{ rhsm.rhsm_server_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: installed
    validate_certs: no
  tags:
    - satellite
    - rhsm

- name: Register to Satellite
  vars:
    rhsm_org_id: "{{ rhsm.rhsm_org_id  | default(omit) }}"
    rhsm_activationkey: "{{ rhsm.rhsm_activationkey  | default(omit) }}"
    rhsm_server_hostname: "{{ rhsm.rhsm_server_hostname  | default(omit) }}"
    rhsm_repositories: "{{ rhsm.rhsm_repositories | default(omit) }}"
  import_role:
    name: oasis_roles.system.rhsm
  tags:
    - satellite
    - rhsm
...
