---
- name: Check for required variables
  hosts: director
  connection: local
  gather_facts: no
  tasks:
    - block:
        - fail:
            msg: "{{ item }} is not defined"
          when: item is undefined
          loop:
            - "{{ site_name }}"

- import_playbook: ../blocks/add-director-to-site-group.yml

- name: Upload ansible-generated templates
  import_playbook: ../ansible-generated-templates-upload.yml

- name: "openstack undercloud deploy {{ site_name }}"
  import_playbook: ../blocks/openstack-overcloud-deploy.yml
  vars:
    dcn_export: no
    tripleo_overcloud_deploy_stack: "{{ site_name }}"
    tripleo_overcloud_deploy_networks_file: "{{ site[site_name].deploy_networks_file }}"
    tripleo_overcloud_deploy_roles_file: "{{ site[site_name].deploy_roles_file }}"
    tripleo_overcloud_deploy_environment_files: "{{ site[site_name].deploy_environment_files }}"
...
