---
- name: Delete KVM networks
  include_tasks: teardown_networks.yml
  when:
    - teardown_kvm_networks | default(False)

- block:
    - name: Setup host as KVM hypervisor
      include_tasks: setup.yml
      when: not skip_setup | default(False)
    - name: Create KVM networks
      include_tasks: create_networks.yml
  when:
    - not teardown | default(False)
    - not teardown_kvm_networks | default(False)
