- name: Publish a new content view
  hosts: satellite
  gather_facts: no
  tasks:
    - name: 'Publish a new content view. Mandatory extra-variables: content_view, lifecycle_environment'
      theforeman.foreman.katello_content_view_version:
        username: "{{ satellite.admin_username }}"
        password: "{{ satellite.admin_password }}"
        server_url: "{{ satellite.server_url }}"
        validate_certs: no
        organization: "{{ satellite.organization }}"
        content_view: "{{ content_view | mandatory }}"
        lifecycle_environments:
          - "{{ lifecycle_environment | mandatory }}"
      delegate_to: localhost
