---
- name: Wait until redfish is available
  uri:
    url: https://{{ oob.ipaddr }}/redfish/v1/Systems
    url_username: "{{ oob_username }}"
    url_password: "{{ oob_password }}"
    headers:
      Accept: application/json
    validate_certs: false
    force_basic_auth: yes
  register: ss_redfish_result
  ignore_errors: true
  until: ss_redfish_result.status is match('200')
  delay: 10
  retries: 30
...
