---
- name: Run ceph-ansible
  hosts: "{{ ceph_admin_node | default(groups['ceph'].0) }}"
  gather_facts: True
  vars:
    # Which cluster group to operate on
    ceph_automation_username: ceph_ansible
    ceph_admin_node: "{{ groups['ceph'].0 }}"
    ceph_playbook_dir: /usr/share/ceph-ansible
    ceph_playbook: site-container.yml
    ceph_inventory: /etc/ansible/hosts
    ceph_playbook_command: >
      ansible-playbook
      --inventory {{ ceph_inventory }}
      --user {{ ceph_automation_username }}
      {{ ceph_playbook }}
  remote_user: "{{ ceph_automation_username }}"
  tasks:
    - name: Display run command for ceph-ansible
      debug:
        msg: "{{ ceph_playbook_command }}"
        verbosity: 1

    - name: Set Ansible logging for future debugging
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: log_path
        value: /var/log/ansible.log
      become: yes

    - name: Run ceph-ansible
      command: "{{ ceph_playbook_command }}"
      args:
        chdir: "{{ ceph_playbook_dir }}"
      environment:
        ANSIBLE_CONFIG: "{{ ceph_playbook_dir }}/ansible.cfg"
      register: ceph_ansible_playbook_run

    - debug:
        var: ceph_ansible_playbook_run
        verbosity: 1
...
