---
- name: Setup prerequisites for Ceph
  hosts: ceph
  tasks:
    - name: Set hostname
      vars:
        hostname_inject_hosts_files: false
      import_role:
        name: oasis_roles.system.hostname
      tags:
        - hostname

    - include_tasks: ../../generic/rhsm_register_satellite.yml

    - name: Install packages
      vars:
        packages: "{{ rhsm.packages }}"
      yum:
        name: "{{ packages }}"
        state: installed
      tags:
        - packages

    - name: Set firewall
      vars:
        firewalld_zone: "{{ firewalld.firewalld_zone }}"
        firewalld_ports_open: "{{ firewalld.firewalld_ports_open }}"
      import_role:
        name: oasis_roles.system.firewalld

- import_playbook: ../../generic/network_setup.yml
  vars:
    playbook_hosts: ceph
  tags:
    - network
...
