---
- name: Add iSCSI Targets to deployed Ceph Cluster
  hosts: ceph
  gather_facts: False
  become: True
  vars:
    ceph_automation_username: ceph_ansible
    ceph_admin_node: "{{ groups['ceph_dev'].0 }}"
  remote_user: "{{ ceph_automation_username }}"
  pre_tasks:
    - name: Ensure usernames are at least 8 characters
      assert:
        that: "{{ item | length >= 8 }}"
        fail_msg: "ERROR: Minimum length of username '{{ item }}' is 8 characters, currently it is of length {{ item | length }}."
        success_msg: "Minimum length of username '{{ item }}' is at least 8 characters at {{ item | length }}."
      loop:
        - "{{ ceph_discovery_username }}"
        - "{{ ceph_chap_username }}"

    - name: Ensure passwors are at least 12 characters
      assert:
        that: "{{ item | length >= 12 }}"
        fail_msg: "ERROR: Minimum length of password is 8 characters, currently it is of length {{ item | length }}."
        success_msg: "Minimum length of password is at least 12 characters at {{ item | length }}."
      loop:
        - "{{ ceph_discovery_password }}"
        - "{{ ceph_chap_password }}"
      no_log: True

  tasks:
    - when: inventory_hostname is match(ceph_admin_node)
      block:
        - name: Copy playbook to Ceph admin node {{ ceph_admin_node }}
          template:
            src: ../templates/iscsi_target_create.yml.j2
            # variable_start_string: "<<"
            # variable_end_string: ">>"
            dest: ~/iscsi_target_create.yml
        - name: Run playbook on Ceph admin node {{ ceph_admin_node }}
          command: >
            ansible-playbook
              --inventory "rbd-target-api,"
              --connection podman
              {% if ansible_verbosity > 0 %}--verbose{% endif %}
              {% if ansible_verbosity > 1 %}--verbose{% endif %}
              {% if ansible_verbosity > 2 %}--verbose{% endif %}
              {% if ansible_verbosity > 3 %}--verbose{% endif %}
              ~/iscsi_target_create.yml
          environment:
            ANSIBLE_LOG_PATH: ~/iscsi_target_create.log
...