---
- hosts: baremetal
  connection: local
  name: View all storage configuration
  gather_facts: False
  vars:
    idrac_controller: "AHCI.Slot.4-1"

  tasks:
    - name: View all volumes
      dellemc_idrac_storage_volume:
        idrac_ip: "{{ oob.ipaddr }}"
        idrac_user: "{{ oob.username }}"
        idrac_password: "{{ oob.password }}"
        state: "view"
        controller_id: "{{ idrac_controller }}"
      register: view_result

    - debug:
        var: view_result
...