---
- hosts: director
  remote_user: root
  name: Install undercloud and introspect Overcloud nodes
  tasks:
    - name: Remove cloud-init
      dnf:
        name: cloud-init
        state: removed

    - name: Apply director role
      import_role:
        name: director
      tags:
        - director

    - name: Create roles
      become: yes
      become_user: stack
      shell: /home/stack/ansible-generated/scripts/_create_roles.sh
...
