---
- hosts: director
  remote_user: root
  name: Apply base, subscription, and director roles
  tasks:
    - name: Apply director role
      import_role:
        name: director
      tags:
        - director

    - name: Apply customizations
      shell: ~/ansible-generated/scripts/_create_roles.sh
      become: yes
      become_user: stack

    # - name: Set overcloud flavors to use UEFI
    #   shell: |
    #     source /home/stack/stackrc;

    #     openstack flavor set --property capabilities:boot_mode='uefi' control
    #     openstack flavor set --property capabilities:boot_mode='uefi' compute
...
