---
- hosts: test
  connection: local
  name: Get BIOS boot order
  gather_facts: False
  collections:
    - community.general

  vars:
    datatype: BiosBootOrder
    baseuri: "{{ inventory_hostname }}"

  tasks:
  - name: Get device boot order
    redfish_info:
      category: Systems
      command: GetBiosAttributes
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result
...