---
#  vars:
#    one_time_boot_device: VCD-DVD

- block:
    # This uses Dell iDRAC extention to set OneTime boot.
    # I tried every possible method to set OneTime boot without idrac_redfish module but with no success as standard redfish can only set 'Cd' device, which on Dell is explicitly different from the 'iDRACVirtual' or "VCD-DVD" device
    - name: Set iDRAC OneTime VirtualMedia boot
      idrac_redfish_config:
        category: Manager
        command:
          - SetManagerAttributes
        resource_id: "{{ oob.resource_ids.manager }}"
        manager_attributes:
          VirtualMedia.1.BootOnce: Enabled    
          ServerBoot.1.FirstBootDevice: "{{ one_time_boot_device }}"
        baseuri: "{{ oob.ipaddr }}"
        username: "{{ oob.username }}"
        password: "{{ oob.password }}"
      register: onetimeboot_result

    - debug:
        var: onetimeboot_result
        verbosity: 2

    - name: Create BIOS configuration job (schedule BIOS setting update)
      idrac_redfish_command:
        category: Systems
        command: CreateBiosConfigJob
        baseuri: "{{ oob.ipaddr }}"
        username: "{{ oob.username }}"
        password: "{{ oob.password }}"
      tags:
        - configjob
      when: False
  tags:
    - bootorder
  when:
    - "'Dell' in oob.SystemManufacturer"
  # Need to add a check to see if this is an iDRAC redfish device
  #EndBlock
...