- hosts: computes
  gather_facts: no
  become: yes
  tasks:

    ###################
    # Allocated vCPUs
    ###################

    - name: Find the allocated vCPUs
      shell: |
        # Get the sum of all domain CPU vCPUs
        sum=0
        for i in $(virsh list --all --uuid); do
          count=$(virsh dominfo ${i} | grep 'CPU(s)' | awk '{print $2}')
          sum=$(($sum + $count))
        done

        echo ${sum}

      changed_when: false
      register: shell_output

    - set_fact:
        allocated_cpus: "{{ shell_output.stdout }}"

    - name: Sum the allocated vCPUs
      shell: |
        # Build the array of values
        arr=()
        {% for host in groups['computes'] %}
        arr+=("{{ hostvars[host]['allocated_cpus'] }}")
        {% endfor %}

        # Sum the values
        sum=0
        for i in ${arr[@]}; do
          sum=$(($sum + $i))
        done

        echo ${sum}

      args:
        executable: /bin/bash
      changed_when: false
      delegate_to: localhost
      run_once: true
      register: allocated_cpus_sum

    ###################
    # Physical vCPUs
    ###################

    - name: Find the physical vCPUs
      setup:
        gather_subset:
          - hardware

    - name: Sum the physical vCPUs
      shell: |
        # Build the array of values
        arr=()
        {% for host in groups['computes'] %}
        arr+=("{{ hostvars[host]['ansible_processor_vcpus'] }}")
        {% endfor %}

        # Sum the values
        sum=0
        for i in ${arr[@]}; do
          sum=$(($sum + $i))
        done

        echo ${sum}

      args:
        executable: /bin/bash
      changed_when: false
      delegate_to: localhost
      run_once: true
      register: physical_cpus_sum

    ###################
    # OVS Ports
    ###################

    - name: Find the OVS port count
      shell: |
        # Get the sum of all OVS ports
        sum=$(ovs-vsctl show | grep Port | wc -l)

        echo ${sum}

      changed_when: false
      register: shell_output

    - set_fact:
        ovs_ports: "{{ shell_output.stdout }}"

    - name: Sum the allocated vCPUs
      shell: |
        # Build the array of values
        arr=()
        {% for host in groups['computes'] %}
        arr+=("{{ hostvars[host]['ovs_ports'] }}")
        {% endfor %}

        # Sum the values
        sum=0
        for i in ${arr[@]}; do
          sum=$(($sum + $i))
        done

        echo ${sum}

      args:
        executable: /bin/bash
      changed_when: false
      delegate_to: localhost
      run_once: true
      register: ovs_ports_sum

    ###################
    # Output
    ###################

    - debug:
        msg:
          - "Sum of allocated vCPUs: {{ allocated_cpus_sum.stdout }}"
          - " Sum of physical vCPUs: {{ physical_cpus_sum.stdout }}"
          - " vCPU allocation ratio: {{ (allocated_cpus_sum.stdout | int / physical_cpus_sum.stdout | int) | round(2) }}"
          - "      Sum of OVS ports: {{ ovs_ports_sum.stdout }}"
      delegate_to: localhost
      run_once: true

  tags:
    - vcpus



- hosts: controllers[0]
  gather_facts: no
  become: yes
  tasks:
    - name: Find active instance count
      shell: |
        docker exec -it $(docker ps --format "{{ '{{' }}.Names{{ '}}' }}" | grep galera) mysql -sN -u root -D nova -e 'SELECT COUNT(*) FROM instances WHERE vm_state="active";'
      changed_when: false
      register: active_instances

    - name: Find shelved instance count
      shell: |
        docker exec -it $(docker ps --format "{{ '{{' }}.Names{{ '}}' }}" | grep galera) mysql -sN -u root -D nova -e 'SELECT COUNT(*) FROM instances WHERE vm_state="shelved_offloaded";'
      changed_when: false
      register: shelved_instances

    - debug:
        msg:
          - "   Shelved instances: {{ shelved_instances.stdout }}"
          - "    Active instances: {{ active_instances.stdout }}"
          - "Shelved/Active ratio: {{ (shelved_instances.stdout | int / active_instances.stdout | int) | round(2) }}"
      delegate_to: localhost
      run_once: true

  tags:
    - instances
