---
- name: Run RSU command
  command: super-rsu /usr/share/opae/n3000/one-time-update/25G/{{ fpga_rsu_json }} --with-rsu

- name: Reload FPGA info
  include_tasks: facts.yml

- name: Verify build version
  assert:
    that: item == fpga_interim_build
    success_msg: Build version after super-rsu is {{ fpga_interim_build }}
    fail_msg: Build version after super-rsu is {{ fpga_interim_build }}
  loop: "{{ fpga_info.build }}"

- name: Check for sysfs entries
  stat:
    path: /sys/class/fpga/intel-fpga-dev.{{ fpga_idx }}/intel-fpga-fme.0/spi-altera.0.auto/spi_master/spi0/spi0.0/intel-generic-qspi.1.auto
  loop: "{{ fpga_info.pcie }}"
  loop_control:
    index_var: fpga_idx
  register: fpga_sysfs_out
  failed_when: not fpga_sysfs_out.stat.exists

- block:
    - name: Run upgrade command
      command: fpgaotsu /usr/share/opae/n3000/one-time-update/25G/otsu-25G.json --rsu
  rescue:
    - name: Reload FPGA info
      include_tasks: facts.yml
    - name: Rescue - Run upgrade command
      command: fpgaotsu /usr/share/opae/n3000/one-time-update/25G/otsu-25G.json --rsu
      when: fpga_interim_build in fpga_info.build
    - name: Rescue - Run RSU command
      command: super-rsu /usr/share/opae/n3000/super-rsu/2x2x25G/super-rsu-2x2x25G.json --with-rsu
      when: fpga_known_versions.n3000_2.prod.build in fpga_info.build

- name: Run update verification
  command: fpgaotsu /usr/share/opae/n3000/one-time-update/25G/otsu-25G.json --verify
  register: fpga_otu_out

- name: Check verification result
  assert:
    that: fpga_otu_out.stdout is search('ONE-TIME SECURE UPDATE OK')
    success_msg: fpgaotsu command indicated successful update
    fail_msg: fpgaotsu command did not indicate successful update

- name: Reload FPGA info
  include_tasks: facts.yml

- name: Verify build version
  assert:
    that: item == fpga_known_versions.n3000_2.prod.build
    success_msg: Build version after super-rsu is {{ fpga_known_versions.n3000_2.prod.build }}
    fail_msg: Build version after super-rsu is {{ fpga_interim_build }}
  loop: "{{ fgpa_info.build }}"
...
