---
- name: Add director host to the Ansible group of the site being added
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    # Check for required variables
    - block:
        - fail:
            msg: "{{ item }} is not defined"
          when: item is undefined
          loop:
            - "{{ site_name }}"

    - name: Set site_to_add fact
      set_fact:
        site_to_add: "site_{{ site_name }}"

    - name: Add director host to the correct site group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ group_names + [site_to_add] }}"
...
