- name: openstack undercloud install
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    # Gather_facts for tripleo_operator_ansible
    - setup:
        gather_subset: '!all'

    - name: 4.7. Installing director
      block:
        - name: 4.7. Copy undercloud.conf to /home/stack
          copy:
            src: /home/stack/ansible-generated/undercloud.conf
            dest: /home/stack/undercloud.conf
            mode: preserve
            remote_src: yes

        - name: 4.7. openstack undercloud install
          import_role:
            name: tripleo.operator.tripleo_undercloud_install
          vars:
            tripleo_undercloud_install_home_dir: /home/stack
            tripleo_undercloud_install_log_output: false
            tripleo_undercloud_install_debug: true
            tripleo_rc_file: /home/stack/stackrc

        - debug:
            var: tripleo_undercloud_install_result

      tags:
        - '4.7'
        - install
