---
- name: openstack overcloud deploy
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    # Check for required variables
    - block:
        - fail:
            msg: "{{ item }} is not defined"
          when: item is undefined
          loop:
            - "{{ tripleo_overcloud_delete_name }}"

    # Gather_facts for tripleo_operator_ansible
    - setup:
        gather_subset: '!all'

    - name: Create folder to hold log output
      file:
        path: /home/stack/ansible-generated-logs
        state: directory
        mode: '0755'

    # Attempt to delete the overcloud.
    # If success, print the stack status
    # If failure, print the failures
    - block:
        - name: openstack overcloud delete {{ tripleo_overcloud_delete_name }}
          import_role:
            name: tripleo.operator.tripleo_overcloud_delete
          vars:
            tripleo_overcloud_delete_debug: true
            tripleo_overcloud_delete_home_dir: /home/stack
            tripleo_overcloud_delete_log: "/home/stack/ansible-generated-logs/overcloud-delete-{{ tripleo_overcloud_delete_name }}.log"
            tripleo_overcloud_delete_log_output: true

        - debug:
            var: tripleo_overcloud_delete_result.stdout_lines

        - name: openstack stack list
          shell: |
            source ~/stackrc && \
            openstack stack list
          register: shell_output
          changed_when: false

        - debug:
            var: shell_output.stdout_lines
          changed_when: false

      rescue:
        - name: openstack stack failures list
          shell: |
            source ~/stackrc && \
            openstack stack failures list {{ tripleo_overcloud_delete_name }} | \
            sed 's/\\n/\n/g'
          register: shell_output
          changed_when: false

        - debug:
            var: shell_output.stdout_lines
          changed_when: false
