resource_registry:
# Configure Networks
{% for role in loop_index.roles %}
{%   if role.type.name_upper == 'Controller'%}
{%     set prepend_name = 'Controller' %}
{%   else %}
{%     set prepend_name = role.type.name_upper + loop_index.name_upper %}
{%   endif %}
  OS::TripleO::{{ prepend_name }}::Net::SoftwareConfig:
    ../network/nic-{{ role.type.name_lower }}-{{ loop_index.name_lower }}.yaml
{% endfor %}

# Disable Swift
  OS::TripleO::Services::SwiftProxy: OS::Heat::None
  OS::TripleO::Services::SwiftStorage: OS::Heat::None
  OS::TripleO::Services::SwiftRingBuilder: OS::Heat::None

parameter_defaults:

  NovaComputeAvailabilityZone: {{ loop_index.name_lower }}
  RootStackName: {{ loop_index.name_lower }}

  NeutronBridgeMappings:
    - tenant:br-tenant
    - datacentre:br-ex
    - ovs-{{ loop_index.name_lower }}:br-provider
    - floating-ips:br-float

  VipSubnetMap:
    ctlplane: ctlplane-subnet

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - NUMATopologyFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

{% for role in loop_index.roles %}
{%   if role.type.name_upper == 'Controller'%}
{%     set prepend_name = 'Controller' %}
{%   else %}
{%     set prepend_name = role.type.name_upper + loop_index.name_upper %}
{%   endif %}
  #
  # {{ prepend_name }}
  #

  {{ prepend_name }}Count: {{ role.count }}
  Overcloud{{ prepend_name }}Flavor: {{ role.type.name_lower }}-{{ loop_index.name_lower }}
  {{ prepend_name }}ControlPlaneSubnet: ctlplane-subnet

  {{ lookup('template', role.environment_file) | indent(2) }}
{% endfor %}
