resource_registry:
# Configure Networks
{% for role in loop_index.roles %}
  OS::TripleO::{{ role.type.name_upper }}{{ loop_index.name_upper }}::Net::SoftwareConfig:
    ../network/nic-{{ role.type.name_lower }}-{{ loop_index.name_lower }}.yaml
{% endfor %}

parameter_defaults:
  NovaComputeAvailabilityZone: {{ loop_index.name_lower }}
  RootStackName: {{ sites[0].name_lower }}

  NeutronBridgeMappings:
    - tenant:br-tenant
    - ovs-{{ loop_index.name_lower }}:br-{{ loop_index.name_lower }}

{% for role in loop_index.roles %}
  #
  # {{ role.type.name_upper }}{{ loop_index.name_upper }}
  #

  {{ role.type.name_upper }}{{ loop_index.name_upper }}Count: {{ role.count }}
  Overcloud{{ role.type.name_upper }}{{ loop_index.name_upper }}Flavor: {{ role.type.name_lower }}-{{ loop_index.name_lower }}
  {{ role.type.name_upper }}{{ loop_index.name_upper }}ControlPlaneSubnet: {{ loop_index.name_lower }}

  {{ lookup('template', role.environment_file) | indent(2) }}
{% endfor %}
