---
- name: Reboot server
  redfish_command:
    category: Systems
    command: 
      - PowerGracefulRestart
    resource_id: "{{ oob.resource_ids.system }}"
    baseuri: "{{ oob.ipaddr }}"
    username: "{{ oob_username }}"
    password: "{{ oob_password }}"
  register: reboot_result

- debug:
    var: reboot_result
    verbosity: 1
...