---
- block:
    - name: Slurp SSH private key
      slurp:
          src: "{{ tower_credential_ssh.key_data_file }}"
      become: False
      delegate_to: localhost
      register: tower_credential_ssh_key_data

    - name: Add SSH Credential to Tower
      tower_credential:
        name: "{{ tower_credential_ssh.name }}"
        ssh_key_data: "{{ tower_credential_ssh_key_data['content'] | b64decode }}"
        kind: "{{ tower_credential_ssh.kind }}"
        organization: "{{ tower_org }}"
        username: "{{ ansible_user }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
        validate_certs: False

    - name: Slurp SCM private key
      slurp:
          src: "{{ tower_credential_scm.key_data_file }}"
      become: False
      delegate_to: localhost
      register: tower_credential_scm_key_data

    - name: Add SCM Credential to Tower
      tower_credential:
        name: "{{ tower_credential_scm.name }}"
        kind: "{{ tower_credential_scm.kind }}"
        username: "{{ tower_credential_scm.username }}"
        ssh_key_data: "{{ tower_credential_scm_key_data['content'] | b64decode }}"
        organization: "{{ tower_org }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
        validate_certs: False
  when: tower_config_type is match('Minimal')
...