---
- name: Upload ansible-generated templates
  import_playbook: ../ansible-generated-templates-upload.yml

- name: openstack overcloud node import
  import_playbook: ../blocks/openstack-overcloud-node-import.yml
  vars:
    tripleo_overcloud_node_import_environment_file: /home/stack/ansible-generated/instackenv.yaml
  tags:
    - openstack overcloud node import

- name: Map Neutron ports to baremetal nodes
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    - name: Map Neutron ports to baremetal nodes
      shell: /home/stack/ansible-generated/scripts/_map_neutron_ports.sh
  tags:
    - map neutron ports

- name: openstack overcloud node introspect
  import_playbook: ../blocks/openstack-overcloud-node-introspect.yml
  tags:
    - openstack overcloud node introspect

- name: Create roles for Overcloud nodes
  hosts: director
  become: yes
  become_user: stack
  gather_facts: no
  remote_user: root
  tasks:
    - name: Create roles for Overcloud nodes
      become: yes
      become_user: stack
      shell: /home/stack/ansible-generated/scripts/_create_roles.sh
  tags:
    - create roles

- name: openstack overcloud deploy central
  import_playbook: ../blocks/openstack-overcloud-deploy.yml
  vars:
    dcn_export: no
    tripleo_overcloud_deploy_stack: central
    tripleo_overcloud_deploy_networks_file: "{{ site.central.deploy_networks_file }}"
    tripleo_overcloud_deploy_roles_file: "{{ site.central.deploy_roles_file }}"
    tripleo_overcloud_deploy_environment_files: "{{ site.central.deploy_environment_files }}"
  tags:
    - openstack overcloud deploy central

- name: openstack aggregate create central
  import_playbook: ../blocks/openstack-aggregate-create.yml
  vars:
    aggregate_name: central
    zone_name: central
  tags:
    - openstack aggregate create

- name: Tempest run
  import_playbook: ../misc/tempest-run.yml
  vars:
    site_name: central
    network_name: management-central-net
  tags:
    - tempest run
...
