---
- name: Destroy Ceph KVM VMs
  hosts: kvm_hypervisor
  gather_facts: False
  vars:
    ceph_vms_to_destroy: "{{ groups['ceph_dev'] }}"
  tasks:
    - name: Debug | Destroying KVM VM for hosts '{{ ceph_vms_to_destroy }}'
      debug:
        var: ceph_vms_to_destroy
        verbosity: 1

    - include_role:
        name: kvm_vm
      vars:
        kvm_vm: "{{ hostvars[vm].kvm_vm }}"
        kvm_vm_dir: "{{ hostvars[vm].kvm_vm_dir }}"
        kvm_vm_root_password: "{{ hostvars[vm].kvm_vm_root_password }}"
        teardown_ceph_secondry_disks: True
        teardown: True
      loop: "{{ ceph_vms_to_destroy }}"
      loop_control:
        loop_var: vm
      tags:
        - setup
...
